apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: hello
spec:
  template:
    spec:
      containers:
      - image: docker.io/csantanapr/helloworld-go
        env:
        - name: TARGET
          value: "Go Sample v1"
