apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: trigger-foo-bar
spec:
  filter:
    sourceAndType:
      type: com.example.bar.foo
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: event-display